# Numpy Part-2

In [ ]:
import numpy as np

### 4. Operation

In [ ]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [ ]:
# 모든 요소들의 합
a.sum()

78

In [ ]:
# 열의 합
a.sum(axis=0)

array([15, 18, 21, 24])

In [ ]:
# 행의 합
a.sum(axis=1)

array([10, 26, 42])

In [ ]:
np.sum(a[0])

10

In [ ]:
a.min(axis=0)

array([1, 2, 3, 4])

In [ ]:
a.max(axis=1)

array([ 4,  8, 12])

In [ ]:
a.mean()

6.5

In [ ]:
a.mean(axis=0), a.mean(axis=1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

- sorting

In [ ]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [ ]:
np.sort(b)      # axis = 1, ascending order

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [ ]:
np.sort(b, axis=0)

array([[ 1,  3,  1,  7],
       [ 2,  5,  5,  9],
       [ 4, 12, 11, 14]])

In [ ]:
b.sort()

In [ ]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [ ]:
b.sort(axis=0)
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [ ]:
# 내림차순
c = np.array([42, 38, 12, 25])
np.sort(c)[::-1]

array([42, 38, 25, 12])

In [ ]:
np.argsort(c)

array([2, 3, 1, 0])

In [ ]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

In [ ]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

- Mathematical functions

In [ ]:
# sigmoid 함수
def sigmoid(x):
    return 1. / (1 + np.exp(-x))

In [ ]:
X = np.array([-10,0,10])
sigmoid(X)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose(전치)

In [ ]:
 b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [ ]:
b.T

array([[ 1,  1,  3],
       [ 2,  4,  9],
       [ 5,  5, 11],
       [ 7, 12, 14]])

- concatenate, vstack, hstack

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [ ]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### 5. Array operation

- 4칙연산

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a + a

array([[2, 4],
       [6, 8]])

In [ ]:
a - a

array([[0, 0],
       [0, 0]])

In [ ]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
a / a

array([[1., 1.],
       [1., 1.]])

- Brodcasting

In [ ]:
a + 3

array([[4, 5],
       [6, 7]])

- Dot product

In [ ]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7, 13).reshape(3,2)

In [ ]:
np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

In [ ]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [ ]:
np.dot(np.array([1,2,3]), np.array([4,5,6]))

32

### 6. Comparison

- all & any

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
np.any(a>5)     # 하나라도 True가 있으면 True

True

In [ ]:
np.all(a>5)     # 모두가 True이여 True

False

- Logical operation

In [ ]:
b = np.logical_and(a > 3, a < 7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [ ]:
np.logical_or(a > 7, a < 3)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [ ]:
a.argmax(), np.argmax(a)

(9, 9)

In [ ]:
a.argmin(), np.argmin(a)

(0, 0)

### 7. Boolean & Fancy indexing

In [ ]:
# array a 에서 값이 6 이상인 것만 가져오기 - filtering
a[a>=6]

array([6, 7, 8, 9])

In [ ]:
a >=6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [ ]:
a[b]

array([4, 5, 6])

- fancy indexing

In [ ]:
a = np.array([2,4,6,8])
b = np.array([0,0,1,3,2,1])         # a의 인덱스값
a[b]

array([2, 2, 4, 8, 6, 4])

### 8. 기술 통계

In [ ]:
a = np.random.randn(10)
a

array([-1.40300052,  0.25963122,  0.83805006,  0.85351394,  1.60765618,
        0.08790155, -0.05758005, -0.66247599,  1.34271704, -1.85866737])

In [ ]:
# 평균
np.mean(a), a.mean()

(0.10077460740374848, 0.10077460740374848)

In [ ]:
# 표준편차(standard deviation)
np.std(a), a.std()

(1.079679860999301, 1.079679860999301)

In [ ]:
# 최소, 최대
a.min(), a.max()

(-1.8586673735924626, 1.6076561847825543)

In [ ]:
# 4분위수
np.percentile(a,25), np.percentile(a,50), np.percentile(a,75)

(-0.51125200645382, 0.17376638664760807, 0.849647972147263)

In [ ]:
#  중앙값
np.median(a)

0.17376638664760807

In [ ]:
a = np.random.randint(0,3,100)
a

array([1, 2, 0, 0, 2, 2, 2, 2, 1, 1, 0, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 1,
       0, 1, 1, 1, 0, 2, 1, 2, 1, 0, 2, 1, 0, 2, 0, 1, 1, 1, 1, 2, 1, 2,
       0, 1, 1, 0, 0, 2, 1, 1, 0, 0, 0, 2, 0, 2, 2, 1, 0, 0, 2, 2, 2, 1,
       2, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 0, 2, 0, 2, 1, 0, 1, 1, 0, 2, 2,
       0, 2, 2, 2, 2, 0, 0, 0, 1, 0, 1, 2])

In [ ]:
# 0, 1, 2의 갯수
np.unique(a, return_counts=True)

(array([0, 1, 2]), array([32, 33, 35]))