In [2]:
import numpy as np

### 연습문제 1번

In [ ]:
a = np.arange(10,81,10).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [3]:
# 해설
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 연습문제 2번

In [8]:
m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

- 연습문제 2-1

In [ ]:
m[1,2]

7

- 연습문제 2-2

In [ ]:
m[2,4]

14

- 연습문제 2-3

In [ ]:
m[1, 1:3]

array([6, 7])

In [6]:
# 2찬원으로 만들려면
m[1:2, 1:3]

array([[6, 7]])

- 연습문제 2-4

In [ ]:
m[1:3, 2]

array([ 7, 12])

- 연습문제 2-5

In [ ]:
m[:2, 3:]

array([[3, 4],
       [8, 9]])

### 연습문제 3번

In [9]:
f = m.faltten()
f

AttributeError: ignored

In [10]:
f = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]], dtype=np.float32)
f

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]], dtype=float32)

- 연습문제 3-1

In [11]:
f[f % 3 == 0]

array([ 0.,  3.,  6.,  9., 12.], dtype=float32)

- 연습문제 3-2

In [12]:
f[f % 4 == 1]

array([ 1.,  5.,  9., 13.], dtype=float32)

- 연습문제 3-3

In [13]:
f[np.logical_and(f%3==0, f%4==1)]

array([9.], dtype=float32)

### 연습문제 4번

In [ ]:
# 모르겠습니다;;;

In [32]:
# 해설
np.eye(5,5,-1,int)*3 + np.eye(5,5,0,int)*2 + np.eye(5,5,1,int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

### 연습문제 5번

In [ ]:
a = np.random.rand(5, 6)
a

array([[0.75696241, 0.28475976, 0.38312761, 0.96157016, 0.92963517,
        0.8356421 ],
       [0.31849542, 0.94672057, 0.35322441, 0.98210988, 0.66171664,
        0.06744003],
       [0.68433653, 0.47813489, 0.12668554, 0.92374161, 0.40874218,
        0.36713395],
       [0.13618787, 0.09769615, 0.85839432, 0.60173984, 0.28870786,
        0.39027214],
       [0.80590103, 0.45670874, 0.48874797, 0.34269334, 0.46653794,
        0.37346052]])

In [23]:
# 해설
np.random.seed(2022)
m = np.random.uniform(0,10,30).reshape(5,6).round(4)
m

array([[0.0936, 4.9906, 1.1338, 0.4997, 6.8541, 4.8699],
       [8.9766, 6.4745, 8.9696, 7.2113, 8.3135, 8.2757],
       [8.3358, 9.5704, 3.6804, 4.9484, 3.3951, 6.1943],
       [9.7753, 0.9643, 7.4421, 2.925 , 2.9868, 7.5247],
       [0.1866, 5.2374, 8.6444, 3.8884, 2.1219, 4.7518]])

- 연습문제 5-1

In [ ]:
a.sum()

15.777226568043838

In [24]:
# 해설
m.max()

9.7753

- 연습문제 5-2

In [25]:
m.sum(axis=1)

array([18.4417, 48.2212, 36.1244, 31.6182, 24.8305])

- 연습문제 5-3

In [26]:
m.max(axis=1)

array([6.8541, 8.9766, 9.5704, 9.7753, 8.6444])

- 연습문제 5-4

In [27]:
m.mean(axis=0)

array([5.47358, 5.44744, 5.97406, 3.89456, 4.73428, 6.32328])

- 연습문제 5-5

In [31]:
m.min(axis=0)

array([0.0936, 0.9643, 1.1338, 0.4997, 2.1219, 4.7518])

### 연습문제 6번

In [ ]:
x = np.array([[ 1, 2, 3, 4], [ 46, 99, 100, 71], [ 81, 59, 90, 100]])
x

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
# 잘 모르겠습니다.
np.sort(x)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [35]:
# 해설
score = np.array([[ 1, 2, 3, 4], [ 46, 99, 100, 71], [ 81, 59, 90, 100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [36]:
# 영어 성적을 argsort()
indices = np.argsort(score[1])
indices

array([0, 3, 1, 2])

In [37]:
# 내림차순
indices[::-1]

array([2, 1, 3, 0])

In [38]:
# 모든 행을 영어성적 내림차순 기준으로 정렬
score[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [39]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### 연습문제 7번

In [ ]:
a = np.random.randint(1, 7, size=100)
a

array([5, 3, 1, 5, 5, 1, 3, 5, 5, 2, 6, 4, 6, 4, 4, 6, 6, 5, 1, 6, 5, 6,
       1, 6, 6, 4, 4, 3, 1, 4, 6, 1, 2, 4, 3, 6, 3, 1, 6, 3, 1, 5, 2, 6,
       5, 4, 1, 5, 6, 4, 5, 5, 1, 2, 1, 4, 6, 5, 6, 3, 2, 4, 3, 6, 1, 2,
       3, 1, 3, 5, 2, 5, 3, 6, 6, 2, 5, 2, 4, 3, 2, 5, 5, 2, 4, 5, 3, 5,
       1, 2, 4, 4, 3, 1, 3, 3, 3, 2, 2, 1])

In [40]:
# 해설
np.random.seed(2022)
dice = np.random.randint(1, 7, 100)
dice

array([6, 5, 6, 1, 2, 2, 1, 1, 3, 1, 1, 6, 2, 2, 4, 4, 4, 1, 4, 1, 4, 1,
       6, 1, 3, 3, 4, 2, 3, 1, 6, 6, 2, 6, 6, 5, 1, 3, 3, 3, 4, 5, 6, 2,
       3, 5, 1, 6, 6, 5, 3, 6, 1, 6, 6, 6, 6, 6, 1, 4, 4, 3, 5, 1, 2, 5,
       2, 1, 6, 6, 1, 1, 4, 2, 6, 4, 3, 2, 6, 3, 2, 5, 2, 3, 3, 2, 6, 2,
       3, 2, 5, 4, 1, 5, 5, 5, 5, 1, 2, 3])

In [41]:
np.mean(dice)

3.47

In [42]:
# dice array에서의 고유값
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [43]:
# dice array에서의 고유값 및 그 갯수
np.unique(dice, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([20, 17, 16, 12, 13, 22]))

In [45]:
unique, counts = np.unique(dice, return_counts=True)
dict(zip(unique, counts))

{1: 20, 2: 17, 3: 16, 4: 12, 5: 13, 6: 22}

### 연습문제 8번

In [ ]:
# 잘 모르겠습니다.

In [46]:
# 5개만 먼저 테스트
np.random.seed(2022)
rate = np.random.normal(0, 0.01, 5)
price = 10000
for i in range(5):
    price = np.round(price * (1 + rate[i]))
    print(int(price), end=' ')

10000 9973 9959 10157 10186 

In [48]:
# 위에서 구한 이자율(%)
rate

array([-5.27899086e-06, -2.74901425e-03, -1.39285562e-03,  1.98468616e-02,
        2.82109326e-03])

In [56]:
# 250개 정규분포, 리스트 활용
np.random.seed(2022)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_list = []
for i in range(250):
    price = price + np.round(price * rate[i])
    price_list.append(price)

price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658], dtype=int32)

In [55]:
# 정규분포, 어레이 활용
np.random.seed(2022)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price * rate[i])
    price_array[i] = price

price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658], dtype=int32)

In [54]:
# 표준정규분포를 이용한 경우
np.random.seed(2022)
rate = np.random.randn(250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price * rate[i]*0.01)
    price_array[i] = price

price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658], dtype=int32)

In [ ]:
%%shell
jupyter nbconvert --to html /content/drive/MyDrive/"Colab Notebooks"/u_Numpy_심사문제.ipynb

[NbConvertApp] Converting notebook /content/drive/MyDrive/Colab Notebooks/u_Numpy_심사문제.ipynb to html
[NbConvertApp] Writing 299537 bytes to /content/drive/MyDrive/Colab Notebooks/u_Numpy_심사문제.html
