In [2]:
import numpy as np
import pandas as pd

### 1. 시리즈 생성

- Numpy 1차원 배열 + 인덱스

In [3]:
pop = [9904312, 3448737, 2890451, 2466052]      # 서울, 부산, 인천, 대구
pop[0], pop[2]

(9904312, 2890451)

In [4]:
metro = pd.Series(pop, index=['서울','부산','인천','대구'])
metro

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [10]:
# 값 하나를 인덱싱할 경우
metro[0], metro['서울']

(9904312, 9904312)

In [11]:
# 여러값을 가져올 경우 - 시리즈 형식
metro[[0,1]]

서울    9904312
부산    3448737
dtype: int64

In [12]:
metro[['서울', '부산']]

서울    9904312
부산    3448737
dtype: int64

In [13]:
# 아래와 같이 사용하면 에러 발생
metro['서울', '부산']

KeyError: ignored

In [8]:
# metro 데이터 타입
metro.values, type(metro.values)

(array([9904312, 3448737, 2890451, 2466052]), numpy.ndarray)

In [14]:
dice = pd.Series(np.random.randint(1,7,10))
dice

0    5
1    4
2    1
3    3
4    2
5    1
6    6
7    1
8    6
9    4
dtype: int64

In [15]:
# 시리즈 데이터는 넘파이 어레이으므로 수식을 바로 적용할 수 있음
metro / 1000000

서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
dtype: float64

In [16]:
dice * 10

0    50
1    40
2    10
3    30
4    20
5    10
6    60
7    10
8    60
9    40
dtype: int64

### 2. 시리즈와 딕셔너리

In [18]:
# 딕셔너리와 키가 시리즈의 인덱스가 됨
city = {'서울':9631482, '부산':3393191, '인천':2632035, '대전':1490158}
metro2 = pd.Series(city)
metro2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [19]:
for key, value in metro2.items():
    print(key, value)

서울 9631482
부산 3393191
인천 2632035
대전 1490158


In [20]:
metro - metro2

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [21]:
# 무한대, 결측치 --> 실수
a = np.array([np.inf, np.nan, 0, 1, 2])
a

array([inf, nan,  0.,  1.,  2.])

### 3. 속성

In [22]:
metro.values

array([9904312, 3448737, 2890451, 2466052])

In [23]:
metro.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [24]:
metro

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [25]:
metro.name = '광역시'
metro

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 광역시, dtype: int64

### 4. Method

- count, unique, nunique, value_counts

In [26]:
dice

0    5
1    4
2    1
3    3
4    2
5    1
6    6
7    1
8    6
9    4
dtype: int64

In [28]:
#element의 갯수
dice.count()

10

In [29]:
# 고유한 값
dice.unique()

array([5, 4, 1, 3, 2, 6])

In [30]:
# 고유한 값의 갯수
dice.nunique()

6

In [31]:
# 고유한 값별로 갯수
dice.value_counts()

1    3
4    2
6    2
5    1
3    1
2    1
dtype: int64

- sum, min, max, mean

In [32]:
dice.sum(), dice.min(), dice.max(), dice.mean()

(33, 1, 6, 3.3)

In [33]:
metro.mean()

4677388.0

In [34]:
# 요약통계
metro.describe()

count    4.000000e+00
mean     4.677388e+06
std      3.507776e+06
min      2.466052e+06
25%      2.784351e+06
50%      3.169594e+06
75%      5.062631e+06
max      9.904312e+06
Name: 광역시, dtype: float64

- Sorting

In [35]:
# 데이터를 기준으로 오름차순
metro.sort_values()

대구    2466052
인천    2890451
부산    3448737
서울    9904312
Name: 광역시, dtype: int64

In [37]:
# 데이터를 기준으로 내림차순
metro.sort_values(ascending=False)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 광역시, dtype: int64

In [38]:
metro.sort_values()[::-1]

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 광역시, dtype: int64

In [39]:
metro.sort_index()

대구    2466052
부산    3448737
서울    9904312
인천    2890451
Name: 광역시, dtype: int64

- 결측치(Na, NaN, Null) 처리 - isna, fillna, dropna

In [41]:
dm = metro - metro2
dm

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [42]:
dm.isna()

대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [43]:
dm.isnull()

대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [44]:
# 0이 아닌 값이 나오면 결측치가 있음
dm.isna().sum()

2

In [46]:
# metro에는 결측치가 없음
metro.isnull().sum()

0

In [47]:
# 결측치를 평균으로 대체
dm.fillna(dm.mean())

대구    195597.333333
대전    195597.333333
부산     55546.000000
서울    272830.000000
인천    258416.000000
dtype: float64

In [48]:
# 결측치를 중앙값으로 대체
dm.fillna(dm.median())

대구    258416.0
대전    258416.0
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [50]:
# 결측치를 0으로 대체하고 타입을 정수형으로 변경
dm.fillna(0).astype(int)

대구         0
대전         0
부산     55546
서울    272830
인천    258416
dtype: int64

In [51]:
# 결측치 제거
dm.dropna()

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

- inplace option

In [52]:
dm

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [53]:
dm2 = dm.dropna()
dm2

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [54]:
dm.dropna(inplace=True)
dm

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [56]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [58]:
age = titanic['age']
age.isna().sum(), age.count()

(177, 714)